
package bank.soap.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapBankImpl", targetNamespace = "http://soap.bank/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapBankImpl {


    /**
     * 
     * @param amount
     * @param accountB
     * @param accountA
     * @throws OverdrawException_Exception
     * @throws IOException_Exception
     * @throws InactiveException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.TransferResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/transferRequest", output = "http://soap.bank/SoapBankImpl/transferResponse", fault = {
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.bank/SoapBankImpl/transfer/Fault/InactiveException"),
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/transfer/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://soap.bank/SoapBankImpl/transfer/Fault/OverdrawException")
    })
    public void transfer(
        @WebParam(name = "accountA", targetNamespace = "")
        String accountA,
        @WebParam(name = "accountB", targetNamespace = "")
        String accountB,
        @WebParam(name = "amount", targetNamespace = "")
        double amount)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOwner", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetOwner")
    @ResponseWrapper(localName = "getOwnerResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetOwnerResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/getOwnerRequest", output = "http://soap.bank/SoapBankImpl/getOwnerResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/getOwner/Fault/IOException")
    })
    public String getOwner(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetAccountResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/getAccountRequest", output = "http://soap.bank/SoapBankImpl/getAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/getAccount/Fault/IOException")
    })
    public String getAccount(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountNumbers", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetAccountNumbers")
    @ResponseWrapper(localName = "getAccountNumbersResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetAccountNumbersResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/getAccountNumbersRequest", output = "http://soap.bank/SoapBankImpl/getAccountNumbersResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/getAccountNumbers/Fault/IOException")
    })
    public List<Object> getAccountNumbers()
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeAccount", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.CloseAccount")
    @ResponseWrapper(localName = "closeAccountResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.CloseAccountResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/closeAccountRequest", output = "http://soap.bank/SoapBankImpl/closeAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/closeAccount/Fault/IOException")
    })
    public boolean closeAccount(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @param amount
     * @throws OverdrawException_Exception
     * @throws IOException_Exception
     * @throws InactiveException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.WithdrawResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/withdrawRequest", output = "http://soap.bank/SoapBankImpl/withdrawResponse", fault = {
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.bank/SoapBankImpl/withdraw/Fault/InactiveException"),
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/withdraw/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://soap.bank/SoapBankImpl/withdraw/Fault/OverdrawException")
    })
    public void withdraw(
        @WebParam(name = "number", targetNamespace = "")
        String number,
        @WebParam(name = "amount", targetNamespace = "")
        double amount)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isActive", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.IsActive")
    @ResponseWrapper(localName = "isActiveResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.IsActiveResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/isActiveRequest", output = "http://soap.bank/SoapBankImpl/isActiveResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/isActive/Fault/IOException")
    })
    public boolean isActive(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns double
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.GetBalanceResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/getBalanceRequest", output = "http://soap.bank/SoapBankImpl/getBalanceResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/getBalance/Fault/IOException")
    })
    public double getBalance(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @param amount
     * @throws IOException_Exception
     * @throws InactiveException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deposit", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.DepositResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/depositRequest", output = "http://soap.bank/SoapBankImpl/depositResponse", fault = {
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.bank/SoapBankImpl/deposit/Fault/InactiveException"),
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/deposit/Fault/IOException")
    })
    public void deposit(
        @WebParam(name = "number", targetNamespace = "")
        String number,
        @WebParam(name = "amount", targetNamespace = "")
        double amount)
        throws IOException_Exception, InactiveException_Exception
    ;

    /**
     * 
     * @param owner
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.jaxws.client.CreateAccountResponse")
    @Action(input = "http://soap.bank/SoapBankImpl/createAccountRequest", output = "http://soap.bank/SoapBankImpl/createAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/SoapBankImpl/createAccount/Fault/IOException")
    })
    public String createAccount(
        @WebParam(name = "owner", targetNamespace = "")
        String owner)
        throws IOException_Exception
    ;

}
